"""add_snapshots_and_peak_rank

Revision ID: 1a1267c7cf3d
Revises: 793f6b7d4330
Create Date: 2026-02-17 17:03:37.131979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a1267c7cf3d'
down_revision: Union[str, Sequence[str], None] = '793f6b7d4330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champion_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('champions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('primary_role', sa.String(length=10), nullable=True),
    sa.Column('secondary_role', sa.String(length=10), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_champion_snapshots_player_time', 'champion_snapshots', ['player_id', 'recorded_at'], unique=False)
    op.create_table('rank_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('queue_type', sa.String(length=20), nullable=False),
    sa.Column('tier', sa.String(length=15), nullable=True),
    sa.Column('division', sa.String(length=5), nullable=True),
    sa.Column('lp', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rank_snapshots_player_time', 'rank_snapshots', ['player_id', 'recorded_at'], unique=False)
    op.alter_column('player_champions', 'games_played',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_champions', 'wins',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('player_champions', 'losses',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_champions_player'), table_name='player_champions')
    op.create_index(op.f('ix_player_champions_player_id'), 'player_champions', ['player_id'], unique=False)
    op.add_column('players', sa.Column('peak_solo_tier', sa.String(length=15), nullable=True))
    op.add_column('players', sa.Column('peak_solo_division', sa.String(length=5), nullable=True))
    op.add_column('players', sa.Column('peak_solo_lp', sa.Integer(), nullable=True))
    op.alter_column('players', 'region',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'EUW1'::character varying"))
    op.alter_column('players', 'is_lft',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('players', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('players', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('players_slug_key'), 'players', type_='unique')
    op.drop_index(op.f('ix_players_slug'), table_name='players')
    op.create_index(op.f('ix_players_slug'), 'players', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_slug'), table_name='players')
    op.create_index(op.f('ix_players_slug'), 'players', ['slug'], unique=False)
    op.create_unique_constraint(op.f('players_slug_key'), 'players', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('players', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('players', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('players', 'is_lft',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('players', 'region',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'EUW1'::character varying"))
    op.drop_column('players', 'peak_solo_lp')
    op.drop_column('players', 'peak_solo_division')
    op.drop_column('players', 'peak_solo_tier')
    op.drop_index(op.f('ix_player_champions_player_id'), table_name='player_champions')
    op.create_index(op.f('idx_champions_player'), 'player_champions', ['player_id'], unique=False)
    op.alter_column('player_champions', 'losses',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_champions', 'wins',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('player_champions', 'games_played',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_rank_snapshots_player_time', table_name='rank_snapshots')
    op.drop_table('rank_snapshots')
    op.drop_index('idx_champion_snapshots_player_time', table_name='champion_snapshots')
    op.drop_table('champion_snapshots')
    # ### end Alembic commands ###
